### ISSUE TITLE
To save or not to save

### ISSUE THREAD

**Issue by duanecosta** [PASTAplus/ezEML#1]
The web app needs to be evaluated with regard to its "save/don't save" behavior. Are the "Save Changes" and "Back" buttons providing appropriate functionality to the end user, or is it confusing? Are there alternative approaches to saving state than the current approach of writing to the file system?

**Comment by mobb** [comment]
Saving (for work in progress) is not clear.
The web app appears to be saving in the background (I see a blue box labeled "save:True"). 
There is also a dropdown EML Document > Save. 
I have not seen a "save changes" button yet (new session after a rather long break). 
the Back button returns to the previous screen (with some ostensibly saved content), but without an understanding of the save-behavior, I was reluctant to push it.

**Comment by mobb** [comment]
If Save is left up to the user: after a save, return to the form user was on when she chose to Save (default now is to go back to the start)

**Comment by jon-ide** [comment]
All of these issues have been addressed.
