### ISSUE TITLE
Custom (i.e. “Other”) text remains in Intellectual Rights after attempting to clear it and change to pre-written option

### ISSUE THREAD

**Issue by gkamener** [PASTAplus/ezEML#104]
[Example ezEML package download](https://tinyurl.com/24v62pzs)

ezEML does not seem to remove existing custom (i.e. “Other”) text from Intellectual Rights when the user attempts to change to pre-written CC BY or CC0 options.

I noticed this possible bug when trying to fetch and update an old package that needed to have the intellectual rights updated to CC BY, and the output (after my attempt to clear the old text and select CC BY in ezEML) contained both the old text and the new CC BY text. If this is not a bug, would it be possible to add functionality to clear existing text?

In an attempt to simplify replicating the issue, I did the following (screenshots also include below):
1.	Create new “test” package in ezEML
2.	Navigate to Intellectual Rights page
3.	Select Other and enter “test” into the text field
4.	Select Save and Continue
5.	Navigate back to Intellectual Rights page
6.	Highlight the “test” text in the field and remove with backspace
7.	Select CC BY option
8.	Save and Continue
9.	Download EML file and review

01_enter_custom_test_rights_before_saving
![01_enter_custom_test_rights_before_saving](https://user-images.githubusercontent.com/37986044/234707176-d48e1000-900a-455f-a08d-a35dc3683584.png)

02_attempt_to_delete_custom_test_rights_and_change_to_cc_by
![02_attempt_to_delete_custom_test_rights_and_change_to_cc_by](https://user-images.githubusercontent.com/37986044/234707211-fc1641ef-74f9-4f25-9c55-99091ff2f566.png)

03_eml_output_after_changing_custom_test_rights_to_cc_by
![03_eml_output_after_changing_custom_test_rights_to_cc_by](https://user-images.githubusercontent.com/37986044/234707223-410e808b-ffae-415b-92c7-a2db2f5e3dcc.png)

**Comment by jon-ide** [comment]
Fixed in release 2023.04.26. Thanks for the detailed bug report!
