### ISSUE TITLE
Attempting to export ezEML data package results in error page

### ISSUE THREAD

**Issue by gkamener** [PASTAplus/ezEML#106]
ezEML errors out when user attempts to export ezEML data package. This applies to previously  saved projects and to newly created ones.

Steps to replicate:

1. Open existing package or create a new one (new one created for screenshots below).
![Screenshot 2023-05-07 at 14-57-21 Title - ezEML Metadata Editor](https://user-images.githubusercontent.com/37986044/236697282-3f290194-f34a-41cc-8fec-bb89241fbb3a.png)

2. Select Export ezEML Data Package
![Screenshot 2023-05-07 at 14-58-19 Title - ezEML Metadata Editor](https://user-images.githubusercontent.com/37986044/236697301-d3b65702-4347-41d5-93a3-8459dcfba96a.png)

3. Arrive at error page
![Screenshot 2023-05-07 at 14-58-35 https __ezeml edirepository org](https://user-images.githubusercontent.com/37986044/236697319-5d0f64c4-6fa7-40ac-9fbf-ae22744307c0.png)

**Comment by jon-ide** [comment]
Fixed in release 2023.05.07.
