### ISSUE TITLE
ezEML sometimes includes "description" element instead of "stmml:description" for custom units after cloning columns

### ISSUE THREAD

**Issue by gkamener** [PASTAplus/ezEML#107]
[Example ezEML package download](https://tinyurl.com/2lo6ljh6)

When custom units are used, ezEML sometimes includes a "description" element instead of "stmml:description" in additional metadata after cloning columns. This behavior has appeared in cases where a user needs to upload a new version of a table that either has newly added columns or the number and order of columns have otherwise changed. I've included a link to the package I initially fetched and have linked the example data file containing a new column order.

[LT_ND_Grahl_003_new_order.csv](https://github.com/PASTAplus/ezEML/files/11511620/LT_ND_Grahl_003_new_order.csv)

1. Fetch existing package ([knb-lter-fce.1069.14](https://portal.edirepository.org/nis/metadataviewer?packageid=knb-lter-fce.1069.14) in this case) that contains metadata for custom units that cover table data. The image below depicts EML from the fetched package, and both the custom units have the expected "stmml:description". The second one is circled because that's what will unexpectedly change later.
![Screenshot 2023-05-18 162814](https://github.com/PASTAplus/ezEML/assets/37986044/3fb9713a-f4ae-40c9-9ee0-e6ae70bdee30)

2. Navigate to Data Table Page
![Screenshot 2023-05-18 at 15-22-08 Data Tables - ezEML Metadata Editor](https://github.com/PASTAplus/ezEML/assets/37986044/c2aafae5-3f87-41d6-9ce3-5a8a69d2c129)

3. Use “Load Data Table from CSV File” option to upload an updated file where new columns have been added, or the column order has been changed (using latter case for this simple example).
![Screenshot 2023-05-18 at 15-26-59 Data Tables - ezEML Metadata Editor](https://github.com/PASTAplus/ezEML/assets/37986044/77a1b0f0-36f4-4413-866a-3a1f26f13b6e)

5. Select Column Properties from another Data Table, and open the current data package for cloning
![Screenshot 2023-05-18 at 15-24-48 https __ezeml edirepository org](https://github.com/PASTAplus/ezEML/assets/37986044/b83e087f-5738-4be8-b17f-b8e7c204b0b6)

6. Clone all columns from the original CSV file
![Screenshot 2023-05-18 at 15-26-32 https __ezeml edirepository org](https://github.com/PASTAplus/ezEML/assets/37986044/a938e3ee-a0b5-4f99-9df5-632528251917)

8. Remove original CSV file that we cloned from
![Screenshot 2023-05-18 at 15-27-10 Data Tables - ezEML Metadata Editor](https://github.com/PASTAplus/ezEML/assets/37986044/2ab70cfd-9ae8-466b-9f33-6a77f9a1b221)

9. Export EML and review. “stmml:description” is present for the first custom unit, but it appears as just “description” for the second custom unit
![EML_output](https://github.com/PASTAplus/ezEML/assets/37986044/90a6583b-6744-4d56-a5df-a79af90b532c)

**Comment by jon-ide** [comment]
Fixed in ezEML release 2023.05.31. Thanks, Gabe, for the very detailed error report.
