### ISSUE TITLE
Using the 'Check data table' tool on a data table with quotation marks in the title causes an internal server error

### ISSUE THREAD

**Issue by bmcafee** [PASTAplus/ezEML#108]
When using the 'Check data table' tool on a data table titled "1962 0.2-acre ("Bourdo") plots" I received the "An error has occurred when processing your request. Please contact support@edirepository.org for assistance. This is an internal server error, probably due to a bug in the ezEML software..." screen. This happened when logged into my account, bmcafee, at a few points throughout the morning of 5/22/23.

Changing the name of the data table to "1962 0.2-acre (Bourdo) plots" avoided the error.

Uploading to the EDI data portal with the quotation marks works perfectly fine so this is a low-priority issue.

**Comment by jon-ide** [comment]
Fixed in ezEML release 2023.05.31.
