### ISSUE TITLE
mechanism to clear one form field

### ISSUE THREAD

**Issue by mobb** [PASTAplus/ezEML#11]
I needed to clear one field from the attribute form (standardUnit), which was filled out in error.
My choices are to (a) reset the whole form or to (b) fill out the custom field in addition to the standard field and hope for the best.
I chose (b). and it worked (customUnit overrode standardUnit). but it's a bit of a leap of faith. Better to let me clear the standardUnit first.

**Comment by jon-ide** [comment]
Obsolete issue. The standard unit dropdown list includes an empty value as the first choice. That lets you clear the standard unit.
