### ISSUE TITLE
Enhancing Data Package Linking: Declare Revisions During Submission

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#118]
We have encountered a recurring problem where data package submissions are inadvertently published as new [data package series](https://edirepository.org/resources/the-data-package#versioning-data-packages) instead of being published as revisions to existing ones. This leads to data discovery issues, as data users may not be aware of the updated packages, causing fragmentation in data access.

This issue typically arises due to either a lack of communication from the author regarding the nature of the submission or an oversight on the part of data curators to request this information. As a result, information is lost, and suboptimal actions are taken.

To mitigate this problem, we propose implementing a solution within the "Submit Package to EDI" page of ezEML. Specifically, we suggest introducing a simple yes/no radio button for submitters to answer the question: "Is this submission an update to an existing data package?" 

If the submitter selects "yes," an additional text field would appear, prompting them to provide the data package's URL, DOI, or data package identifier.

The information gathered through this inquiry would be sent along with the submission to support@edirepository.org, making it readily available for curators to review and act upon.

Thoughts?

**Comment by jon-ide** [comment]
Sounds like a great idea. Should be easy to add...

**Comment by clnsmth** [comment]
Thanks for considering this @jon-ide.

If you think it might be helpful, I'd be happy to bring this up in the team meeting this week to get other perspectives on it and   then summarize the conversation back here.

**Comment by jon-ide** [comment]
Doesn't seem controversial...

**Comment by clnsmth** [comment]
Hi @jon-ide, the changes applied in 7ef5c45c3060f6c77e3add55b0d581fa9fbb8601 look great!

What do you think about setting the initial state of the radio buttons to be _off/unselected_ and then validating that the user has selected one or other options before the submission is allowed to pass? 

This would catch the case where a rushed user mistakenly overlooks the prompt.

**Comment by jon-ide** [comment]
I've made the change @clnsmth suggested, to leave the radio buttons unselected by default and check that a selection is made. Thanks for the suggestion!

**Comment by clnsmth** [comment]
This looks great @jon-ide, thanks.
