### ISSUE TITLE
Link direct from ezEML to portal's preview EML?

### ISSUE THREAD

**Issue by hubbardbrook** [PASTAplus/ezEML#123]
This would be an incredibly useful feature. Now one needs to download EML from ezEML, go to portal, click on tools/preview, navigate to EML file, click to preview. Imagine if there was a 'preview EML' on the left sidebar of ezEML that would take you to a preview in one click....

**Comment by jon-ide** [comment]
Just a note: this would entail configuring ezEML servers with the CSS, etc. as expected by the preview pages so the pages can be rendered on the ezEML server. Not impossible, of course, but it will take a little doing.

**Comment by hubbardbrook** [comment]
That sounds way more involved than what I was imagining when I posted. I thought there might be a way to pass that xml to the existing previewer on portal and maybe open in a new tab. If that sort of solution doesn't exist, you probably have more important things to work on.
Mary

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by jon-ide** [comment]
Roger Dahl came up with an elegant way to implement this. Added in release 2023.11.08.
