### ISSUE TITLE
When re-uploading an Other entity, one gets selected name has already been used.

### ISSUE THREAD

**Issue by jlaundre** [PASTAplus/ezEML#187]
In re-uploading an other entity in an EML document which was fetched from EDI I get - "The selected name has already been used in this data package. Names of data tables and other entities must be unique within a data package." 

If I edit the entity and changed the "Source Name" I can re-upload the changed file without an error.  However, the "Source Name" is not updated to the filename of the uploaded file.  The eml does evaluate OK, but it will have the wrong objectName.

This behavior doesn't occur with a data table file.

**Comment by jon-ide** [comment]
Fix released in release 2024.02.21
