### ISSUE TITLE
Need all content entered to be displayed

### ISSUE THREAD

**Issue by vanderbi** [PASTAplus/ezEML#21]
Maybe this is a matter of taste, but I find it confusing.

I entered a First and Last name for a Creator.  Then I click "back" since that seems to be how one can non-intuitively possibly save something in this editor.  Then I want to add an email address and some other info about the Creator.  So I "Edit" the Creator and add content.  Then I click "back" and I return to the Creator screen that still only shows the First and Last name.  Was the new content saved or not?  It would be helpful if the screen displayed all the Creator content.

**Comment by jon-ide** [comment]
The creators list is a table of contents, in effect. It shows the creator's name (or organization or position if there is no name) to identify the item in the list. There are a number of fields potentially associated with a creator. Displaying them all in the list would somewhat defeat the purpose. It's really just a table of contents, or index.
