### ISSUE TITLE
Support input of text file with list of taxa for taxonomic coverages

### ISSUE THREAD

**Issue by jon-ide** [PASTAplus/ezEML#32]
A user could create a list of taxa and taxonomic authorities in CSV format and then load it into ezEML, which would go through and process them all, filling in the taxonomic hierarchies, etc.

This is potentially a bit complex to implement. It would be a long-running task, so probably would want to be implemented as an asynchronous, background task. Ideally, the user would see some indication of progress. Error-handling may be tricky: some taxa may process just fine but others may encounter errors, and this would need to be reported back to the user. How best to do this if the processing is asynchronous? TBD.

**Comment by clnsmth** [comment]
Could maybe address the "long-running task"  issue with reference to a local copy of taxonomic authorities like [the taxadb R package](https://cran.r-project.org/web/packages/taxadb/index.html).

**Comment by jon-ide** [comment]
In 2022.09.28 release of ezEML.
