### ISSUE TITLE
Support provenance metadata

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#39]
The documentation of provenance metadata is an important and growing need of data publishers. Consider supporting provenance at the dataset level of an EML record for internal (to PASTA) and external data sources.

**Comment by clnsmth** [comment]
I just received a request for this feature from some folks at IEP and recently processed a dataset my self, via ezEML, in which I had to manually construct the provenance. Would be great to have this feature built in to this awesome metadata editor!

**Comment by jon-ide** [comment]
Enhanced in release 2021.07.07. The group decided that the way to handle this was to modify Method Step to add an optional "Data Sources" field. In the generated metadata, a section is appended to the Method Step description. If the Data Sources entry is "My data source... 2021", for example, the following is appended to the Method Step description:

                    <para></para>
                    <para>==================== Data Sources =========================</para>
                    <para>My data source... 2021</para>
                    <para>===========================================================</para>

It will be up to the data curator to modify the EML appropriately.
