### ISSUE TITLE
Mitigate issues related data entity versions

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#40]
When a data entity changes from the original version uploaded to ezEML (via **Load Data Table From CSV File** and **Load Other Entity From File**), then version specific metadata (e.g. checksum, file size, etc.) may no longer be valid and cause issues during the evaluate/upload step.

To mitigate this, add a clause to the user help button:

... In the latter case, a number of the [Data Table/Other Entity] characteristics will be automatically extracted or inferred from the file, but some others will still need to be entered or modified manually. _**NOTE: The file will have to be re-uploaded if any changes are made to it (some extracted metadata is version specific).**_ ...

If not prominent enough, consider adding as a pop-up message when the **Load From ...** buttons are pushed.

**Comment by jon-ide** [comment]
Fixed in release 2021.03.17.
