### ISSUE TITLE
Bug: Required role for creator/contact

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#44]
Importing a creator/contact (i.e. a responsible party that does not require a role) into an associated party/project personnel (i.e. responsible party that does require a role) raises a validation error in the respective creator/contact. Until such an import the creator/contact does not have such issues.

**Comment by jon-ide** [comment]
Fixed in release 2021.02.17. It was a side-effect of bugs in the copy() method in metapype.node.
