### ISSUE TITLE
Enhancement: Recalculate column attributes after changing type

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#45]
When a user manually changes a column type (e.g. Text to Categorical, or Text to DateTime), ezEML should recalculate/fetch categorical codes and datetime format strings for the user rather than expecting them to do it. This feature is already called upon initial table upload and thus, in some sense, is an expected behavior.

**Comment by clnsmth** [comment]
Has this enhancement been implemented @jon-ide?

**Comment by jon-ide** [comment]
Fixed in release 2021.03.17.

**Comment by clnsmth** [comment]
Thanks @jon-ide!
