### ISSUE TITLE
Bug: Estimator of Categorical types is too sensitive

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#47]
When a column contains few numeric values (e.g. count of petals on a flower), then it is estimated to be categorical. From my experience the vast majority of categorical variable types are text (e.g. a, b, c, etc.) not numbers. Consider using this info to refine the estimator.

**Comment by jon-ide** [comment]
In release 2021.03.17, I've tweaked the heuristic for inferring the column type a bit. I think it's worth noting, though, that inferring the type to be categorical when it should be numerical is less onerous to the user than the other way around. To change a variable from numerical to categorical, the user has to enter all of the category codes, so it's a multi-step process. To go the other way, the user just has to change the type from categorical to numerical.

**Comment by clnsmth** [comment]
> To change a variable from numerical to categorical, the user has to enter all of the category codes, so it's a multi-step process.

But this is no longer the case since implementation of #45, correct?

**Comment by jon-ide** [comment]
Good point, clnsmth! :-) 

I'll reopen.

**Comment by jon-ide** [comment]
In Release 2021.03.24, a column containing numbers is considered Numerical unless the number of distinct values is <= 5.
