### ISSUE TITLE
Size element should include the appropriate unit declared in the "unit" attribute

### ISSUE THREAD

**Issue by servilla** [PASTAplus/ezEML#48]
The size element in the physical sub-tree should include the `unit` attribute correctly defined for the corresponding value. It cannot be assumed to be byte for any downstream use of the metadata element.

![image](https://user-images.githubusercontent.com/2224723/109210971-d0e77300-776a-11eb-8ea5-a6a6c116c533.png)

**Comment by jon-ide** [comment]
Fixed in release 2021.03.17
