### ISSUE TITLE
Bug: empty taxonomicRankName when manually specified

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#53]
When filling hierarchy for "Robina pseudoacacia" using ITIS, a virtually-empty return is presented to the user. Manually selecting the "Species" Taxon Rank, then Save and Continue, results in an empty taxonomicRankName element in the downloaded EML.

**Comment by clnsmth** [comment]
Running into this issue again, but now the name of the saved organism is not showing up in the web-form displayed list of Taxonomic Coverage unless I back out, "Add Taxonomic Coverage", enter the "Taxon Scientific Name", select "Taxon Rank", and THEN "Save and Continue". 

Attempting to "Fill Hierarchy" and then when it fails to resolve to the "Taxonomic Authority", manually specifying the "Taxon Rank", creates some state that prevents "Save and Continue" from adding the taxon to the list.

**Comment by jon-ide** [comment]
Fixed in Release 2021.08.05.
