### ISSUE TITLE
Potential NoneType Error

### ISSUE THREAD

**Issue by nwallin1** [PASTAplus/ezEML#54]
It looks like in the load_eml function (see _Code Example 2_ below), the return value can be 'None' (I'm not sure if in practice this ever occurs)

If 'None is returned, then in the _Code Example 1_ below,  `eml_node = None` and attempting to call `eml_node.find_child(names.DATASET) ` would throw an error

A check to see if eml_node is None would prevent this error.

_Code Example 1_
https://github.com/PASTAplus/ezEML/blob/9b45a57df6267daf4a54ddc261388b1d1c28ee96/webapp/home/views.py#L1541-L1542
_Code Example 2_
https://github.com/PASTAplus/ezEML/blob/9b45a57df6267daf4a54ddc261388b1d1c28ee96/webapp/home/metapype_client.py#L870

**Comment by jon-ide** [comment]
The file being read by load_eml contains the current state of the model. I.e., it always exists, barring cosmic rays or some catastrophic failure. load_eml is called in about 100 places in the code, and if the file doesn't exist for some reason there really isn't a graceful failure mode other than to tell the user that the system is broken. So, I'm inclined to leave it as is.

**Comment by gkamener** [comment]
@jon-ide I might have run into something related to this issue in ezEML today, but I can't replicate it. I'm noting it here just for the record. On an initial attempt to fetch package knb-lter-fce.1256.3 from EDI, ezEML gave the following error: "Unable to fetch package data: 'NoneType' object has no attribute 'find_all_descendants'". I tried fetching the package again a couple times after that, and it loaded just fine.
