### ISSUE TITLE
Strip leading and trailing white space from user inputs

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#56]
I can't think of an instance in which this shouldn't be done.

Currently, the presence of a leading or trailing white space attached to a Taxon Scientific Name prevents matches (e.g. "  Myrmica fracticornis" does not resolve but "Myrmica fracticornis" does).

**Comment by jon-ide** [comment]
Fixed in Release 2021.08.05. For now, stripping whitespace just in the case of the Taxon Scientific Name. Need to investigate whether and how this should be done across all user inputs.
