### ISSUE TITLE
Check for missing value code definitions

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#59]
Missing value codes without definition should result in error when a user runs the "Check Metadata" function.

**Comment by clnsmth** [comment]
Just ran into another data submission request with this issue. 

If an error isn't thrown by ezEML's "Check Metadata" function, then the user will hit a cryptic schema validation error in the EDI Data Portal's evaluation/upload step.

**Comment by clnsmth** [comment]
A user just hit this issue on their own when attempting to evaluate/upload to the Data Portal. They got the cryptic message with no understanding of the issues origin then contacted me for help. Fixing this issue would head off a lot of work (and potential frustration) on the users part.

**Comment by clnsmth** [comment]
Hitting this issue again on another ezEML generated publication request.

**Comment by clnsmth** [comment]
Hitting this issue again on another ezEML generated publication request.

**Comment by jon-ide** [comment]
Fixed in Release 2021.08.05. ezEML was creating empty code explanation nodes when the explanation wasn't provided. Validation saw that a node was present, so it didn't mark it as an error.
