### ISSUE TITLE
Categorical information (enumeratedDomain element) without any codes or definitions not in Check Metadata

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/ezEML#66]
Columns can have type "Categorical" without having any code/definition pairs. This leads to an invalid EML file.

![Screen Shot 2021-11-22 at 3 20 33 PM](https://user-images.githubusercontent.com/18039765/142929851-34388379-719a-4099-8cad-a364fe6247ec.png
[Frugivoria_montane_mammal_database.zip](https://github.com/PASTAplus/ezEML/files/7584118/Frugivoria_montane_mammal_database.zip)
)

**Comment by kzollove** [comment]
Another example: [link](https://hideuri.com/JJLjPb)

**Comment by jon-ide** [comment]
Fixed in ezEML release 2022.04.25
