### ISSUE TITLE
Missing value codes should require code explanation

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/ezEML#67]
The following is invalid in EML:

`<missingValueCode>
                        <code>NA</code>
                        <codeExplanation></codeExplanation>
                    </missingValueCode>`

It would be useful for ezEML to either enforce a codeExplanation or fill with a generic text ("missing value")

I'm having trouble attaching an ezEML package, but I can forward the link upon request (Rosemary Hartman's ezEML submission 12/3/21)

**Comment by clnsmth** [comment]
Ditto. Hitting this same issue on a data package submission now. There's no way to point the user back to the specific instances where code explanations are missing. Would be a big help if this were fixed.

**Comment by jon-ide** [comment]
Fixed
