### ISSUE TITLE
new feature request:  make "reupload table" button available when non-ezEML-generated EML doc uploaded

### ISSUE THREAD

**Issue by vanderbi** [PASTAplus/ezEML#73]
Currently, when I upload an EML document generated using the FCE tool in order to add another year of data, I have to upload the new dataset, clone properties from the old dataset to the new dataset, and then delete the old dataset.  This is no big deal with the number of attributes is few, but time-consuming when there are 50 plus columns in the dataset.   Having the "re-upload" button available would be easier.

**Comment by jon-ide** [comment]
The re-upload is available if the user clicks Get Associated Data when importing the XML. I added text to make this clearer to the user.
