### ISSUE TITLE
Keywords should not all be assigned to "LTER Keyword Thesaurus" when EML is fetched from EDI

### ISSUE THREAD

**Issue by vanderbi** [PASTAplus/ezEML#76]
When I fetch a data package from EDI, all the keywords seem to be entered into the EML as belonging to the LTER Keyword Thesaurus, even if that is not what is in the original EML.  
I tried erasing the entry in the Keyword Thesaurus (optional) field, and the keywords still get assigned to the LTER Keyword Thesaurus.

**Comment by vanderbi** [comment]
I did some more investigating of the original EML that I imported, and the previous IM had included karst, Mexico, Belize, and other keywords as coming from the LTER Keyword Thesaurus.  So it makes sense that all keywords were assigned to the LTER Keyword Thesaurus when the package was fetched from PASTA.  However, I was unable to change their assignment to a different Thesaurus in the interface.

**Comment by jon-ide** [comment]
Fixed in release 2022.04.26.
