### ISSUE TITLE
Strange behavior when entering Personnel info

### ISSUE THREAD

**Issue by vanderbi** [PASTAplus/ezEML#77]
I imported a data package from an FCE user.  The grad student had added himself as Project personnel, so I deleted him and then wanted to add the PI of FCE, instead.   I entered John Kominoski, and the Organization field autopopulated with "FCE LTER".  John's Email was also autopopulated, but with John.Kunze@ucop.edu.   City, etc. also autopopulated.   

I don't think this autopopulation should be occurring.

**Comment by jon-ide** [comment]
This was a client-side issue caused by autofill in Firefox. Not an ezEML issue.
