### ISSUE TITLE
Get Associated Data Files (Fetch a Package from EDI) not working for edi.836.1

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/ezEML#79]
Clicking the Get Associated Data Files button causes and error (Email support@environmentaldatainitiative.org message) for [edi.836.1](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.836.1). Continue without getting data files option works without error

**Comment by jon-ide** [comment]
A data file contains illegal characters that cause a UnicodeDecodeError exception. Now it will bring up a page that identifies the illegal characters, rather than going to the generic error screen. Fixed in release 2022.05.02.
