### ISSUE TITLE
A contribution to the ezEML User Guide?

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#80]
Hi @jon-ide. Below is some content we were going to add to web-x but seems more appropriate for the ezEML User Guide section on [Starting from an ezEML Document Template](https://ezeml.edirepository.org/static/user_guide/templates.pdf?version=2022.04.26). This could fit nicely under the "Creating Templates" section. Take it or leave it. 🙂 

## Design considerations for ezEML templates

When designing an ezEML template (or a series of ezEML templates), consider who will likely be using your template and which facets of EML will remain constant among that user base. Some examples of ezEML template designs:
 * A single template for a project that every dataset associated with the project should use could pre-fill information regarding funding information, point-of-contact, principal investigator, intellectual rights, and keywords. Whenever a scientist needs to publish their data from this project, the information manager can refer them to the same template.
 * Multiple templates for a field station could be broken down based on the geographic location of the sites. For example, the Piedraroja Field Station could have one template for each of the three stream sensor sites that produce data. While all templates share project-wide information, they each have a different geographic coverage. The template that a data collector from this field station would use depends on the location of their study.

An important thing to remember about ezEML templates is that their simplicity is their power. Since an ezEML template is really just a partially-filled ezEML data package, you have the freedom to design a suite of templates to best suit your organization's needs. A template that only pre-fills one or two fields goes along way to ensure that data is standardized across your organization. Finally, remember that a data author can augment, delete, or overwrite fields in a template if necessary. Consider developing lightweight documentation or how-to guides to inform your organization's data authors on the best way to utilize your templates.

**Comment by jon-ide** [comment]
Added a slightly edited version to the User Guide in release 2022.04.29.
