### ISSUE TITLE
No option to close modal dialogue window after fetching data package from EDI

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#82]
A modal dialog window overlays the ezEML interface after importing a data package from EDI. I don't see an option to close this window and am feeling a bit trapped. Maybe others are too?

My web browser is Google Chrome, Version 100.0.4896.127 (Official Build) (x86_64).

**Comment by jon-ide** [comment]
The dialog has a close option, but the dialog is large and, depending on how one has one's screen set up, the close option may be pushed off the top of the screen. I've reduced the text significantly so the close option should always be visible now. Fixed in release 2022.05.02.
