### ISSUE TITLE
Weird behavior from physical metadata fields after Fetch from EDI and Reupload Table

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/ezEML#84]
This ezEML submission ([download](https://ezeml.edirepository.org/user-data/Christina_E._Burdi-092938816e59ab163ee2689526a9c013/exports/edi.1103.1/2022_05_19_13_27_43/edi.1103.1.zip)), which was fetched from [edi.1103.1](https://portal.edirepository.org/nis/mapbrowse?packageid=edi.1103.1) does not contain the physical metadata (md5, file size, number of records) for the two tables that were Re-uploaded by submitter. The original (edi.1103.1) does contain all physical metadata.

To add this information, I downloaded the tables and Re-uploaded to ezEML, which apparently added all of the missing physical information. After this fix, the only lingering problem was that the `method` attribute was not automatically added to the `<authentication>` element for either table.

Seems like two separate strange occurrences, but maybe there is a single underlying issue.

**Comment by jon-ide** [comment]
Unable to reproduce.
