### ISSUE TITLE
Unable to "Send to EDI" or create an archive of package that was Fetched from EDI without data objects

### ISSUE THREAD

**Issue by kzollove** [PASTAplus/ezEML#86]
When fetching from EDI, the user has the option to get associated data files or continue without importing. The option to continue without importing is useful if the user has large data objects or if they simply don't need to edit tables. 

However, say the user has made edits to this ezEML data package and wants to Send to EDI. They are unable to do so unless they imported all associated data objects. This limits the usefulness of Fetch Data Package for data authors (that don't upload their own data to EDI) with large data objects who want to edit their data packages.

The current "workaround" I am suggesting to data authors is to simply download the EML file and attach it to an email to EDI.

I imagine it is a big ask, but could it be made so that an ezEML data package archive can be created without the data objects _as long as_ it has URLs associated with the data objects?

**Comment by jon-ide** [comment]
I believe this is moot now that we use group collaboration with EDI curators rather than Send to EDI.
