### ISSUE TITLE
Fetch from EDI, with data objects, duplicates other entities

### ISSUE THREAD

**Issue by clnsmth** [PASTAplus/ezEML#98]
When fetching a data package from EDI that contains other entities and also opting to fetch the data objects, other entities are duplicated. This doesn't occur when fetching without data objects.

For example, fetching edi.890.1 with data objects results in duplicated other entity "Appendix A". When fetching without data objects "Appendix A" is not duplicated. This behavior was also observed for edi.210.1.

**Comment by jon-ide** [comment]
Fixed in release 2023.01.04.
